server:
  port: 8082 # dfeault 8080
  
spring:
  profiles:
    active: test

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: ${eureka_url}
      
messaging:
  queue: "user_queue"
  exchange: "user_exchange"
  routing_key: "user_routingkey:
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
