server:
  port: 8082 # dfeault 8080
  
spring:
  profiles:
    active: test

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: ${eureka_url}
      
messaging:
  queues: user_queue, login_queue
  exchanges:
    - user_exchange
    - login_exchange
  routing_keys:
    - user_routingkey
    - login_routingkey
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
