server:
  port: 8081 # dfeault 8080
  
spring:
  profiles:
    active: test
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_pass}
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none
  aop:
    auto: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
management:
  endpoints:
    web:
      exposure:
        include: "*"