server:
  port: 8081 # dfeault 8080
  
spring:
  profiles:
    active: test
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none
  aop:
    auto: true
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_pass}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: ${eureka_url}

messaging:
  queues:
    user: 'user_queue'
    login: 'login_queue'
  exchanges:
    user: user_queue
    login: login_queue
  routing_keys:
    user: user_queue
    login: login_queue
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
